### ISSUE TITLE
I cannot run molmap in Spyder IDE

### ISSUE THREAD

**Issue by mohammad-saber** [shenwanxiang/bidd-molmap#10]
Thank you for sharing your great code. 

I can run the example on the "Readme" page of the repository in Jupyter Notebook. But, when I try to run the code in Spyder IDE, I get error in several lines. 

For example, when I run:

```
X = mp.batch_transform(smiles_list,  scale = True, 
                       scale_method = 'minmax', n_jobs=8)
```

I get the following error :

```

Traceback (most recent call last):
  File "/opt/anaconda3/envs/molmap/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/opt/anaconda3/envs/molmap/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/opt/anaconda3/envs/molmap/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/molmap/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/opt/anaconda3/envs/molmap/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/Users/mohammad/Documents/Code/bidd-molmap/molmap/map.py", line 253, in transform
    print_error('please fit first!')
TypeError: func() missing 2 required keyword-only arguments: 'sep' and 'verbose'
"""

TypeError: func() missing 2 required keyword-only arguments: 'sep' and 'verbose'
```

Also, when I run:
`mp.plot_scatter()
`

I get the  error:
`AttributeError: 'MolMap' object has no attribute 'embedded'
`

I don't understand the effect of IDE. This is the first time I see this phenomenon. If you have any idea how to solve this issue, I appreciate it to guide me.

**Comment by shenwanxiang** [comment]
> Thank you for sharing your great code.
> 
> I can run the example on the "Readme" page of the repository in Jupyter Notebook. But, when I try to run the code in Spyder IDE, I get error in several lines.
> 
> For example, when I run:
> 
> ```
> X = mp.batch_transform(smiles_list,  scale = True, 
>                        scale_method = 'minmax', n_jobs=8)
> ```
> 
> I get the following error :
> 
> ```
> 
> Traceback (most recent call last):
>   File "/opt/anaconda3/envs/molmap/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
>     r = call_item()
>   File "/opt/anaconda3/envs/molmap/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
>     return self.fn(*self.args, **self.kwargs)
>   File "/opt/anaconda3/envs/molmap/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
>     return self.func(*args, **kwargs)
>   File "/opt/anaconda3/envs/molmap/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
>     for func, args, kwargs in self.items]
>   File "/opt/anaconda3/envs/molmap/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
>     for func, args, kwargs in self.items]
>   File "/Users/mohammad/Documents/Code/bidd-molmap/molmap/map.py", line 253, in transform
>     print_error('please fit first!')
> TypeError: func() missing 2 required keyword-only arguments: 'sep' and 'verbose'
> """
> 
> TypeError: func() missing 2 required keyword-only arguments: 'sep' and 'verbose'
> ```
> 
> Also, when I run:
> `mp.plot_scatter() `
> 
> I get the error:
> `AttributeError: 'MolMap' object has no attribute 'embedded' `
> 
> I don't understand the effect of IDE. This is the first time I see this phenomenon. If you have any idea how to solve this issue, I appreciate it to guide me.

Sorry, I'm not so farmilar with this, it seems that your "mp" object has not be fit yet, to transform a smiles, the mp object should be fit first
