### ISSUE TITLE
Status of protein sequence features?

### ISSUE THREAD

**Issue by miquelduranfrigola** [shenwanxiang/bidd-molmap#13]
Hi!
Thanks for a fantastic repository.
I see that protein sequence features are available. Unfortunately, I do not find a tutorial for getting those.
Could you please advise on the best way to proceed? Is this work in progress?
Thanks!
M

**Comment by shenwanxiang** [comment]
Hi [miquelduranfrigola](https://github.com/miquelduranfrigola),

You may see two examples here: https://github.com/shenwanxiang/bidd-molmap/tree/master/molmap/test

We will update this soon, thanks!

**Comment by miquelduranfrigola** [comment]
Thanks @shenwanxiang !
