### ISSUE TITLE
Improvement of the Installation instructions

### ISSUE THREAD

**Issue by yotf** [shenwanxiang/bidd-molmap#6]
I want to suggest a little adjustment to the Installation instructions.
Namely, the problem arises when Python> 3.6 is used. 

So the first command should be:
`conda create -c conda-forge -n molmap rdkit python=3.6`

Also conda has an automated way to add a directory to Python path:
`conda develop <directory>`

This will write a conda.pth file to the environment's site-packages directory which will cause the directory to be added to the sys.path.

**Comment by shenwanxiang** [comment]
Thanks for these good suggestions, I have added them
