### ISSUE TITLE
How to set No. of epochs when fitting model?

### ISSUE THREAD

**Issue by mohammad-saber** [shenwanxiang/bidd-molmap#9]
Thank you for sharing your great work. 

I would like to ask if there is any parameter to set "No. of Epochs" when fitting model in this command: 
`clf.fit(trainX, trainY, validX, validY ) `

Thank you.

**Comment by shenwanxiang** [comment]
> Thank you for sharing your great work.
> 
> I would like to ask if there is any parameter to set "No. of Epochs" when fitting model in this command:
> `clf.fit(trainX, trainY, validX, validY ) `
> 
> Thank you.

Hi @mohammad-saber , these parameters can be declared when initializing clf:


clf = RegressionEstimator(n_outputs = xxx, fmap_shape1 = (xx,xx), epochs = 800,)

https://github.com/shenwanxiang/bidd-molmap/blob/master/molmap/model/model.py#L88

**Comment by mohammad-saber** [comment]
Thank you for your help.
